---
title: "Grading with flexible methods"
author: "林茂廷"
output: html_document
params:
  dirSet: "./Exercise1/ans"
  hwcode: "hw1"
  gskey: "16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA"
  gsfileMapping: "1J9A6We6cdDfOT-11gBgbHC9Qzqu0d457aquy5k1IOCc"
  gsPublicKey: "1NespAnPgIdVqtSOntojQpBhoJWbCDN4cnSpqcShc9O0"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tools)
library(purrr)
library(stringr)
library(dplyr)
library(knitr)
library(googlesheets)
gsCorrected<-gs_key(params$gskey)
gsMapping<-gs_key(params$gsfileMapping)

gsPublic<-gs_key(params$gsPublicKey)
wsName<-params$hwcode

dataSubmit <- gs_read(gsMapping,ws=wsName) #學生上傳結果
```

# Convert Rmd to R

**purlInfo** shows if a file fails to be purled. 

```{r convert Rmd to R}
dataSubmit$新檔名 <- paste0(params$dirSet,"/",
                         dataSubmit$新檔名)
listOfRmds <- list_files_with_exts(params$dirSet,"Rmd")
listOfRs <- str_replace(listOfRmds,"Rmd","R")

fileListPurl <- function(ix){
  tryCatch({
    purl(listOfRmds[ix],output=listOfRs[ix])
  },
    error=function(e){
      print(paste0(listOfRmds[ix]," has problems."))
    }
  )
}

map(1:length(listOfRmds),fileListPurl) -> purlInfo

# 無法purl 記在dataSubmit$cannotPurl
purlInfo %>% str_which("has problems") -> cannotPurl_ind
dataSubmit %>% mutate(cannotPurl=(新檔名 %in% listOfRmds[cannotPurl_ind])) -> dataSubmit
listOfRmds<-listOfRmds[-cannotPurl_ind]
listOfRs <- str_replace(listOfRmds,"Rmd","R")
```

```{r chunk name locator}
codeChunkName <- function(codeNameLine){
  str_split_fixed(codeNameLine,
                  "## ----",
                  n=4)[,2]->name2
  str_split_fixed(name2,"---------------------------------------------------------------",
                  n=4)[,1]->nameFinal
  return(nameFinal)
}
```

```{r tryCatch appending function}
appendTryCatch <- function(.x){
  # .x  the path file to append tryCatch()
  ##.x <- listOfRs[1]
  ## 取得每個chunk名稱
  originContent <- readLines(.x)
  
  ## remove setup chunk
  originContent %>% str_which("opts_chunk") -> setupLines
  if(length(setupLines)>0){
    originContent <- originContent[-setupLines]
  }

  nLines<-length(originContent)
  originContent %>% str_which("## ----") -> chunkStartLocs
  lapply(originContent[chunkStartLocs],
        codeChunkName) -> chunkNameList #取得每個chunk的名稱
  
  appendedContent<-originContent[1:chunkStartLocs[1]]
  
  chunkStartLocs <- c(chunkStartLocs,nLines+1)
  for(i in 1:(length(chunkStartLocs)-1)){
    #i <- 1
    startLine <- chunkStartLocs[i]+1
    endLine <- chunkStartLocs[i+1]-1
    chunkContent<-originContent[startLine:endLine]
    appendedContent<-
      c(
        appendedContent,
        "tryCatch({",
        chunkContent,
        "},",
        "error=function(e){}"
      )
    if(chunkNameList[[i]]==""){
      appendedContent<-c(
        appendedContent,
        ")"
      )
    } else {
       appendedContent<-c(
        appendedContent,
        paste0(")","->catchList[['",chunkNameList[i],"']]")
      )
    }
  }
  
  # initiate catchList at top
  appendedContent <- c("catchList <- list()",appendedContent)
  
  # tug name and id at the end
  appendedContent <- c(appendedContent,
    "catchList[['name']]<-params$studentName",
    "catchList[['id']]<-params$studentID")
  
  writeLines(appendedContent,
             con=.x)
  
}
```


## 產生tryCatch學生答案程式檔

```{r create all tryCatch files, message=FALSE, error=FALSE}
map(listOfRs,appendTryCatch)
responseCollection<-list()
ansCollection<-list()
for(i in 1:length(listOfRs)){
  #i<-33
  print(paste0(i,": ",listOfRs[i]))
  tryCatch({
    source(listOfRs[i])
    ansCollection[[i]]<-catchList
  },
  error=function(e){
    ansCollection[[i]]<-"Cannot process"
    }
  )->responseCollection[[i]] 
  
  # 清空name id以免下一個學生是NULL而冠上了前個學生資訊
  params$studentID <- "NA"
  params$studentName <- "NA"
}
```

### 問題

```{r}
# 無法run .R 的位置
cannotProcess_ind <- responseCollection %>% map_lgl(is.character) 
problemRmd<-listOfRmds[cannotProcess_ind]
dataSubmit %>% mutate(cannotSourceR=(新檔名 %in% problemRmd)) ->
  dataSubmit
okListOfRmds<-listOfRmds[!cannotProcess_ind]
okListOfRs <- str_replace(listOfRmds,"Rmd","R")
okAnsCollection <- ansCollection[!cannotProcess_ind]
```

## 對答案

```{r}
upperListOfFiles <- toupper(okListOfRs)
ansLoc<-str_which(upperListOfFiles,"ANS.R")
studentAnswers <- okAnsCollection[-ansLoc]
studentListOfRs <- okListOfRs[-ansLoc]
studentListOfRms <- okListOfRmds[-ansLoc]
correctAnswers <- okAnsCollection[[ansLoc]]
```

```{r}
    ## 彈性改題函數
correctFun <- function(.studentAns_i,.correctAns_i,type="i",method=NULL) {
  switch(type,
         "i" = identical(.studentAns_i,.correctAns_i),
         "b" = all(.studentAns_i %in% .correctAns_i),
         method(.studentAns_i,.correctAns_i)
  )
}
```

```{r}
correctAnswers %>% names -> ansNames
#isolate ansX parts
ansNames %>% str_which("ans") -> ansParts

results<-c()
for(j in 1:length(studentAnswers)){
  #j<-1 #第j個學生
  #j<-9
  studentAnswers_j <- studentAnswers[[j]]
  #print(j)
  result_j<-c()
  for(i in 1:length(ansParts)){
  #第i題
    #i<-2
    #print(i)
    chunkName_i <- ansNames[ansParts[i]] #第i題的chunk name
    # 檢查有無對應改題method
    chunkNumber_i <- str_split_fixed(chunkName_i,"ans",n=2)[,2]
    methodName_i<-paste0("m",chunkNumber_i)
    correctAns_i <- correctAnswers[[chunkName_i]]
    correctMethod_i <- correctAnswers[[methodName_i]]
    
    if(is.character(correctMethod_i)){ #有用字串選內定改法
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i,
                             type=correctMethod_i)
    } else if(is.null(correctMethod_i)){ #沒有設定，用預設identical
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i)
    } else { #自定函數
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i,type="o",
                             method=correctMethod_i)
    }
    result_j<-c(result_j,result_ij)*1
  }
  results <- rbind(results, result_j)
}

colnames(results) <- ansNames[ansParts]
results <- as.data.frame(results)
```

```{r}
studentAnswers %>% map_chr(~.$name) -> results$姓名
studentAnswers %>% map_chr(~as.character(.$id)) -> results$學號
results$新檔名 <- studentListOfRms
#results$檔名 <- studentListOfRs
```

```{r upload result to GS}
#gsMapping %>% gs_read(ws=wsName) -> fileMapping

dataSubmit %>% select(姓名,學號,新檔名,cannotPurl,cannotSourceR) %>%
  mutate(學號=as.character(學號)) %>%
  left_join(results %>% select(-姓名,-學號),by=c("新檔名")) -> mergedResults

mergedResults %>% mutate(
  上傳檔正常=(!cannotPurl & !cannotSourceR)
  ) -> mergedResults
```

```{r, eval=T}
publicResults <-
  mergedResults %>% select(
    -姓名,-新檔名,-cannotPurl, -cannotSourceR
  )
str_split_fixed(mergedResults$新檔名,"ans/",n=2)[,2]->mergedResults$新檔名
  
if(wsName %in% gs_ws_ls(gsCorrected)){
  gs_edit_cells(gsCorrected,ws=wsName,
                input=mergedResults, col_names = TRUE,
                anchor="A1")
  gs_edit_cells(gsPublic,ws=wsName,
                input=publicResults, col_names = TRUE,
                anchor="A1")  
} else {
  gs_ws_new(gsCorrected,ws=wsName,
            input=mergedResults, col_names = TRUE,
            anchor="A1")  
  gs_ws_new(gsPublic,ws=wsName,
              input=publicResults, col_names = TRUE,
              anchor="A1")

}

file.remove(listOfRs)
```

