---
title: "experiment purl"
author: "林茂廷"
date: "10/21/2018"
output: html_document
params:
  dirSet: "./Exercise2/ans"
  hwcode: "hw2"
  gskey: "16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA"
  gsfileMapping: "1J9A6We6cdDfOT-11gBgbHC9Qzqu0d457aquy5k1IOCc"
  gsPublicKey: "1NespAnPgIdVqtSOntojQpBhoJWbCDN4cnSpqcShc9O0"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tools)
library(purrr)
library(stringr)
library(dplyr)
library(knitr)
library(googlesheets)
gsCorrected<-gs_key(params$gskey)
gsMapping<-gs_key(params$gsfileMapping)
gsPublic<-gs_key(params$gsPublicKey)
wsName<-params$hwcode
```

# Convert Rmd to R

**purlInfo** shows if a file fails to be purled. 

```{r convert Rmd to R}
listOfRmds <- list_files_with_exts(params$dirSet,"Rmd")
listOfRs <- str_replace(listOfRmds,"Rmd","R")

fileListPurl <- function(ix){
  tryCatch({
    purl(listOfRmds[ix],output=listOfRs[ix])
  },
    error=function(e){
      print(paste0(listOfRmds[ix]," has problems."))
    }
  )
}

map(1:length(listOfRmds),fileListPurl) -> purlInfo

# 更新可產生的.R 
listOfRs <- list_files_with_exts(params$dirSet,"R")

#map(1:length(listOfRmds),
#    function(x) purl(listOfRmds[x],output=listOfRs[x]))

```

```{r chunk name locator}
codeChunkName <- function(codeNameLine){
  str_split_fixed(codeNameLine,
                  "## ----",
                  n=4)[,2]->name2
  str_split_fixed(name2,"---------------------------------------------------------------",
                  n=4)[,1]->nameFinal
  return(nameFinal)
}
```

```{r tryCatch appending function}
appendTryCatch <- function(.x){
  # .x  the path file to append tryCatch()
  ##.x <- listOfRs[1]
  ## 取得每個chunk名稱
  originContent <- readLines(.x)
  
  ## remove setup chunk
  originContent %>% str_which("opts_chunk") -> setupLines
  if(length(setupLines)>0){
    originContent <- originContent[-setupLines]
  }

  nLines<-length(originContent)
  originContent %>% str_which("## ----") -> chunkStartLocs
  lapply(originContent[chunkStartLocs],
        codeChunkName) -> chunkNameList #取得每個chunk的名稱
  
  appendedContent<-originContent[1:chunkStartLocs[1]]
  
  chunkStartLocs <- c(chunkStartLocs,nLines+1)
  for(i in 1:(length(chunkStartLocs)-1)){
    #i <- 1
    startLine <- chunkStartLocs[i]+1
    endLine <- chunkStartLocs[i+1]-1
    chunkContent<-originContent[startLine:endLine]
    appendedContent<-
      c(
        appendedContent,
        "tryCatch({",
        chunkContent,
        "},",
        "error=function(e){}"
      )
    if(chunkNameList[[i]]==""){
      appendedContent<-c(
        appendedContent,
        ")"
      )
    } else {
       appendedContent<-c(
        appendedContent,
        paste0(")","->catchList[['",chunkNameList[i],"']]")
      )
    }
  }
  
  # initiate catchList at top
  appendedContent <- c("catchList <- list()",appendedContent)
  
  # tug name and id at the end
  appendedContent <- c(appendedContent,
    "catchList[['name']]<-params$studentName",
    "catchList[['id']]<-params$studentID")
  
  writeLines(appendedContent,
             con=.x)
  
}
```


## 產生tryCatch學生答案程式檔

```{r create all tryCatch files, message=FALSE, error=FALSE}
map(listOfRs,appendTryCatch)
responseCollection<-list()
ansCollection<-list()
for(i in 1:length(listOfRs)){
  tryCatch({
    source(listOfRs[i])
    ansCollection[[i]]<-catchList
  },
  error=function(e){
    ansCollection[[i]]<-"Cannot process"
    }
  )->responseCollection[[i]] 
  
  # 清空name id以免下一個學生是NULL而冠上了前個學生資訊
  params$studentID <- "NA"
  params$studentName <- "NA"
}
```

## 對答案

```{r}
upperListOfFiles <- toupper(listOfRs)
ansLoc<-str_which(upperListOfFiles,"ANS.R")
studentAnswers <- ansCollection[-ansLoc]
studentListOfRs <- listOfRs[-ansLoc]
correctAnswers <- ansCollection[[ansLoc]]
correctAnswers %>% names -> ansNames
ansNames[1:(length(ansNames)-2)] -> ansNames

results<-c()
for(i in 1:length(studentAnswers)){
  # 對答案
  #i<-1
  result_i <- map2_int(
            studentAnswers[[i]][ansNames],
            correctAnswers[ansNames],
            identical)
  newResult<-result_i
  
  results <- rbind(results, newResult)
}

results %>% as.data.frame() -> results
studentAnswers %>% map_chr(~.$name) -> results$姓名
studentAnswers %>% map_chr(~.$id) -> results$學號
results$檔名 <- studentListOfRs
```

```{r upload result to GS}
gsMapping %>% gs_read(ws=wsName) -> fileMapping

fileMapping %>% select(姓名,學號) %>%
  mutate(學號=as.character(學號)) %>%
  left_join(results %>% select(-姓名),by=c("學號")) -> mergedResults

mergedResults %>% mutate(
  上傳檔正常=(學號 %in% results$學號)) -> mergedResults
```

```{r, eval=T}
publicResults <-
  mergedResults %>% select(
    -姓名,-檔名
  )
  
if(wsName %in% gs_ws_ls(gsCorrected)){
  gs_edit_cells(gsCorrected,ws=wsName,
                input=mergedResults, col_names = TRUE,
                anchor="A1")
  gs_edit_cells(gsPublic,ws=wsName,
                input=publicResults, col_names = TRUE,
                anchor="A1")  
} else {
  gs_ws_new(gsCorrected,ws=wsName,
            input=mergedResults, col_names = TRUE,
            anchor="A1")  
  gs_ws_new(gsPublic,ws=wsName,
              input=publicResults, col_names = TRUE,
              anchor="A1")

}

file.remove(listOfRs)
```

