---
title: "Grading with flexible methods"
author: "林茂廷"
output: html_document
params:
  dirSet: "./Exercise2/ans"
  hwcode: "hw2"
  gskey: "16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA"
  gsfileMapping: "1J9A6We6cdDfOT-11gBgbHC9Qzqu0d457aquy5k1IOCc"
  gsPublicKey: "1NespAnPgIdVqtSOntojQpBhoJWbCDN4cnSpqcShc9O0"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tools)
library(purrr)
library(stringr)
library(dplyr)
library(knitr)
library(googlesheets)
ENV = new.env(parent = .BaseNamespaceEnv)
# Attache it to the search path so that objects in your environment can be
# found from the global environment (i.e. from the console):
attach(ENV)
# do things:

gsCorrected<-gs_key(params$gskey)
gsMapping<-gs_key(params$gsfileMapping)

gsPublic<-gs_key(params$gsPublicKey)
wsName<-params$hwcode
dirSet <- params$dirSet
dataSubmit <- gs_read(gsMapping,ws=wsName) #學生上傳結果

dataSubmit %>% mutate(shortHWname=file_path_sans_ext(新檔名)) -> dataSubmit
```

# Convert Rmd to R

**purlInfo** shows if a file fails to be purled. 

```{r convert Rmd to R}
file.remove(list_files_with_exts(dirSet,"R"))
file.remove(list_files_with_exts(dirSet,"Rdata"))
dataSubmit$新檔名 <- paste0(params$dirSet,"/",
                         dataSubmit$新檔名)

```

## 檢查Encoding
```{r}
library(purrr)
library(readr)
listOfRmds <- list_files_with_exts(params$dirSet,"Rmd")
map(listOfRmds,readr::guess_encoding) -> encodingGuess
map_chr(encodingGuess,function(x) x$encoding[1]) -> encodingList

dataEncoding <- data.frame(
  Filename = listOfRmds,
  Encoding = encodingList,
  stringsAsFactors = F
)

library(dplyr)
dataEncoding %>%
  filter(Encoding != "UTF-8") -> nonUTF8Rmds
if(nrow(nonUTF8Rmds)!=0){
  for(i in 1:nrow(nonUTF8Rmds)){
    #i<-1
    rawRmd_i<-read_lines(nonUTF8Rmds$Filename[i],locale=locale(encoding=nonUTF8Rmds$Encoding[i]))
    write_lines(rawRmd_i,path=nonUTF8Rmds$Filename[i])
  }
}

## 記錄encoding狀態
dataSubmit %>% 
  left_join(dataEncoding,by=c("新檔名"="Filename")) -> dataSubmit
```


```{r purl to R files}
fileListPurl <- function(ix){
  tryCatch({
    purl(listOfRmds[ix],output=str_replace(listOfRmds[ix],"Rmd","R"))
  },
    error=function(e){
      print(paste0(listOfRmds[ix]," has problems."))
    }
  )
}

map(1:length(listOfRmds),fileListPurl) -> purlInfo

# 無法purl 記在dataSubmit$cannotPurl
purlInfo %>% str_which("has problems") -> cannotPurl_ind
dataSubmit %>% mutate(cannotPurl=(新檔名 %in% listOfRmds[cannotPurl_ind])) -> dataSubmit
```

```{r}
if(length(cannotPurl_ind)>0){ # 有無法purl檔時
  listOfRmds<-listOfRmds[-cannotPurl_ind]
  listOfRs <- str_replace(listOfRmds,"Rmd","R")
}
```

```{r chunk name locator}
codeChunkName <- function(codeNameLine){
  str_split_fixed(codeNameLine,
                  "## ----",
                  n=4)[,2]->name2
  str_split_fixed(name2,"---------------------------------------------------------------",
                  n=4)[,1]->nameFinal
  return(nameFinal)
}
```

## 定義tryCatch學生答案程式檔產生函數

```{r tryCatch appending function}
appendTryCatch <- function(.x){
  # .x  the path file to append tryCatch()
  # .x <- listOfRs[1]
  ## 取得每個chunk名稱
  originContent <- readLines(.x)
  
  ## remove setup chunk
  originContent %>% str_which("opts_chunk") -> setupLines
  if(length(setupLines)>0){
    originContent <- originContent[-setupLines]
  }

  nLines<-length(originContent)
  originContent %>% str_which("## ----") -> chunkStartLocs
  lapply(originContent[chunkStartLocs],
        codeChunkName) -> chunkNameList #取得每個chunk的名稱
  
  appendedContent<-originContent[1:chunkStartLocs[1]]
  
  chunkStartLocs <- c(chunkStartLocs,nLines+1)
  for(i in 1:(length(chunkStartLocs)-1)){
    #i <- 1
    startLine <- chunkStartLocs[i]+1
    endLine <- chunkStartLocs[i+1]-1
    chunkContent<-originContent[startLine:endLine]
    appendedContent<-
      c(
        appendedContent,
        "tryCatch({",
        chunkContent,
        "},",
        "error=function(e){}"
      )
    if(chunkNameList[[i]]==""){
      appendedContent<-c(
        appendedContent,
        ")"
      )
    } else {
       appendedContent<-c(
        appendedContent,
        paste0(")","->catchList[['",chunkNameList[i],"']]")
      )
    }
  }
  
  # initiate catchList at top
  appendedContent <- c("catchList <- list()",appendedContent)
  
  # tug name and id at the end
  appendedContent <- c(appendedContent,
    "catchList[['name']]<-params$studentName",
    "catchList[['id']]<-params$studentID")
  
  # tug catchList saved in Rdata
  RdataName<-paste0(str_split_fixed(.x,".R",n=2)[,1],".Rdata")
  appendedContent <- c(appendedContent,
                       paste0("save(catchList,file='",RdataName,"')"))
  
  # rm list in the front
  appendedContent <- c("rm(list=ls())",appendedContent)
  
  writeLines(appendedContent,
             con=.x)
  
}
```


## 執行tryCatch學生答案程式檔
responseCollection: 執行R檔的結果

```{r create all tryCatch files, message=FALSE, error=FALSE}
listOfRs <- list_files_with_exts(params$dirSet,"R")
map(listOfRs,appendTryCatch)

listOfRs %>% 
  str_split_fixed("ans/",n=2) %>%
  {.[,2]} %>% 
  str_split_fixed(".R",n=2) %>%
  {.[,1]} -> hwNames
listOfSavedTryCatchFiles <-
  paste0(params$dirSet,"/",hwNames,".Rdata")

responseCollection<-vector("list",length=length(listOfRs))# list()
#ansCollection<-vector("list",length=length(listOfRs))# list()
for(i in 1:length(listOfRs)){
  #i<-33
  #print(paste0(i,": ",listOfRs[i]))
  tryCatch(
    {
    # 儲存學生catchList
    # save(catchList,file=listOfSavedTryCatchFiles[i])
    #ansCollection[[i]]<-catchList
    responseCollection[[i]] <- "ok"
    #rm(list=c("catchList"))
    print(paste0(i,": ok, ",listOfRs[i]))
    # 執行學生tryCatch R檔
    source(listOfRs[i],ENV)
    }
    , error=function(e){
    #ansCollection[[i]]<-"Cannot process"
    responseCollection[[i]] <- "Cannot process"
    print(paste0(i,": Fail, ",listOfRs[i]))
    #rm(list=c("catchList"))
    }
  ) 
  
  # 清空name id以免下一個學生是NULL而冠上了前個學生資訊
  params$studentID <- "NA"
  params$studentName <- "NA"
}

# 有些tryCatch R file無法儲存catchList到Rdata
# 記錄可儲存catchList的名單
oklistOfSavedTryCatchFiles <- list_files_with_exts(dirSet,"Rdata")


#ansLoc <- str_which(listOfRs,"-ans.R")
#source(listOfRs[ansLoc])

#source(listOfRs[length(listOfRs)])
```

### 問題

```{r}
# 無法產生 .Rdata 的位置
oklistOfSavedTryCatchFiles %>% 
  file_path_sans_ext() %>%
  paste0(".Rmd") -> okRmd

cannotProcess_ind <- which(!(listOfRmds %in% okRmd)) 
problemRmd<-listOfRmds[cannotProcess_ind]
dataSubmit %>% mutate(cannotSourceR=!(新檔名 %in% okRmd)) ->
  dataSubmit
okListOfRmds<-listOfRmds[!cannotProcess_ind]
okListOfRs <- str_replace(listOfRmds,"Rmd","R")
#okAnsCollection <- ansCollection[!cannotProcess_ind]
```

## 對答案


```{r}
## 彈性改題函數
correctFun <- function(.studentAns_i,.correctAns_i,type="i",method=NULL) {
  switch(type,
         "i" = identical(.studentAns_i,.correctAns_i),
         "b" = (all(.studentAns_i %in% .correctAns_i) &
                  all(.correctAns_i %in% .studentAns_i)),
         method(.studentAns_i,.correctAns_i)
  )
}
```


```{r grade on Rdata}
#listOfSavedTryCatchFiles
upperlistOfSavedTryCatchFiles<-toupper(oklistOfSavedTryCatchFiles)
ansLoc<-str_which(upperlistOfSavedTryCatchFiles,"ANS.RDATA")
studentAnswers <- oklistOfSavedTryCatchFiles[-ansLoc]
load(oklistOfSavedTryCatchFiles[ansLoc])

correctAnswers <- catchList
correctAnswers %>% names -> ansNames
#isolate ansX parts
ansNames %>% str_which("ans") -> ansParts

results<-c()
for(j in 1:length(studentAnswers)){
  #j<-1 #第j個學生
  #j<-9
  #j<-1
  load(studentAnswers[j])
  studentAnswers_j <- catchList
  #print(j)
  result_j<-c()
  for(i in 1:length(ansParts)){
  #第i題
    #i<-1
    #print(i)
    chunkName_i <- ansNames[ansParts[i]] #第i題的chunk name
    # 檢查有無對應改題method
    chunkNumber_i <- str_split_fixed(chunkName_i,"ans",n=2)[,2]
    methodName_i<-paste0("m",chunkNumber_i)
    correctAns_i <- correctAnswers[[chunkName_i]]
    correctMethod_i <- correctAnswers[[methodName_i]]
    
    if(is.character(correctMethod_i)){ #有用字串選內定改法
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i,
                             type=correctMethod_i)
    } else if(is.null(correctMethod_i)){ #沒有設定，用預設identical
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i)
    } else { #自定函數
      result_ij <- correctFun(studentAnswers_j[[chunkName_i]],
                             correctAns_i,type="o",
                             method=correctMethod_i)
    }
    result_j<-c(result_j,result_ij)*1
  }
  results <- rbind(results, result_j)
}

colnames(results) <- ansNames[ansParts]
results <- as.data.frame(results)
```

```{r}
studentAnswers %>%
  basename %>% str_split_fixed(".Rdata",n=2) %>%
  {.[,1]} -> okRdataList

results$shortHWname <- okRdataList
dataSubmit %>% left_join(
  results,by=c("shortHWname")
) %>% mutate(cannotRdata=!(shortHWname %in% results$shortHWname)) -> dataSubmit
```

```{r upload result to GS}
#gsMapping %>% gs_read(ws=wsName) -> fileMapping

dataSubmit %>% select(姓名,學號,新檔名,Encoding,cannotPurl,cannotRdata,starts_with("ans")) %>%
  mutate(學號=as.character(學號))  -> mergedResults

mergedResults %>% mutate(
  上傳檔正常=(!cannotPurl & (Encoding=="UTF-8") & !cannotRdata)
  ) -> mergedResults
```

```{r 成績計算}
# 成績計算
library(magrittr)
mergedResults %>% 
  select_at(vars(starts_with("ans"))) %>%
  transmute(成績=rowSums(.,na.rm = T)/length(ansParts)*5+5) %$%
  成績 -> mergedResults$成績
```

```{r}
# Sort by 學號
mergedResults %>% arrange(學號) -> mergedResults

publicResults <-
  mergedResults %>% select(
    -姓名,-新檔名,-cannotPurl, -cannotRdata
  )

str_split_fixed(mergedResults$新檔名,"ans/",n=2)[,2]->mergedResults$新檔名
```


```{r 上傳GS, eval=F}
if(wsName %in% gs_ws_ls(gsCorrected)){
  gs_edit_cells(gsCorrected,ws=wsName,
                input=mergedResults, col_names = TRUE,
                anchor="A1")
  gs_edit_cells(gsPublic,ws=wsName,
                input=publicResults, col_names = TRUE,
                anchor="A1")  
} else {
  gs_ws_new(gsCorrected,ws=wsName,
            input=mergedResults, col_names = TRUE,
            anchor="A1")  
  gs_ws_new(gsPublic,ws=wsName,
              input=publicResults, col_names = TRUE,
              anchor="A1")

}

file.remove(listOfRs)
```

