---
title: "下載學生GDrive作業"
author: "林茂廷"
date: "11/06/2018"
output: html_document
params:
  deadline: 2018-11-05
  hwcode: Exercise3
  ansDir: "../Exercise3/ans" #放在\Grading_Programs要..
  gsFileNameMapping: "1J9A6We6cdDfOT-11gBgbHC9Qzqu0d457aquy5k1IOCc"
  gsClassInfo: "1E1P2na_-iRzczWxRVa09ldjE9NMidJOX0RGw9muhZfw"
---
!!! 檢查 174 檔案mapping更新 colname 被蓋掉問題
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 引入GS

```{r import g sheets}
library(dplyr)
library(googlesheets)
library(lubridate)
library(stringr)
library(readr)
library(stringr)
library(googledrive)
library(tools)
#gs_auth(new_user = TRUE)

# 引入線上繳件資料
gsSubmit<-gs_key("1G8NjBYgWcQFVT8ms4c5HmWp19V_DvJ5u1rEKVNLRmZs")
dataSubmit0 <- gs_read(gsSubmit,ws="Form Responses 1") 
dataSubmit0 %>% filter(作業代碼==params$hwcode) -> dataSubmit
```

排除已下載的檔案
```{r}
dataSubmit %>% filter(downloaded==1) %>% nrow -> numberOfDownloaded
dataSubmit %>% filter((downloaded !=1 | is.na(downloaded))) -> dataSubmit

if(nrow(dataSubmit)==0){
  stop("沒有新檔案需要下載")
}

dataSubmit %>% transmute(id=paste0(mdy_hms(Timestamp),學號)) %>% .$id -> newDownloadid
```


## 處理資料（含重覆提交問題）

```{r}
# parse Timestamp
dataSubmit$Timestamp %>% mdy_hms(tz="Asia/Taipei") ->
  dataSubmit$Timestamp

# parse deadline
deadlineDateTime <- paste0(params$deadline, " 23:59:59 CST")
deadlineDateTime %>% ymd_hms(tz="Asia/Taipei") -> deadlineDateTime
```

```{r}
# select homework 
dataSubmit %>% filter(
  作業代碼==params$hwcode & Timestamp <= deadlineDateTime) ->
  dataSubmit
```

```{r}
# deal with multiple submissions
dataSubmit %>% group_by(姓名) %>%
  arrange(desc(Timestamp), .by_group=TRUE) %>%
  mutate(有重覆=duplicated(學號)) %>%
  ungroup() -> dataSubmit1
dataSubmit1 %>% filter(有重覆==FALSE) -> dataSubmit
```

## 比對學號輸出正確性

```{r}
ClassInfoSheets <- gs_key(params$gsClassInfo)
gs_read(ClassInfoSheets,ws="LMS") -> dataLMS #數位學苑資料
gs_read(ClassInfoSheets,ws="全班資訊") -> 
  dataAllInfo #含所有回填資訊
dataLMS %>% select(帳號,信箱) %>%
  rename(LMS學號=帳號,
           `Email Address`=信箱) -> idEmailLMS
dataAllInfo %>% select(學號,Gmail) %>%
  rename(
    Survey學號=學號,
    `Email Address`=Gmail) -> 
  idEmailSurvey

# Email有在LMS的, 學號以LMS為準
dataSubmit %>% mutate(
  EmailatLMS=(`Email Address` %in% idEmailLMS$`Email Address`)
  ) -> dataSubmit
dataSubmit %>% left_join(
  idEmailLMS,by=c("Email Address")
) -> dataSubmit

dataSubmit %>%
  mutate(
    學號=ifelse(EmailatLMS == TRUE,LMS學號,學號)
  ) -> dataSubmit
```


## 產生新檔名

```{r creatNewFileName}
library(googledrive)
newNamefun<-function(fileAccessURL,i,numberOfDownloaded){
  programFileId<-as_id(fileAccessURL)
  programFileNameOld<-drive_get(id=programFileId)$name
  programFileNameExtension<-file_ext(programFileNameOld)
  programFileNameNew<-paste0(params$hwcode,"_",i+numberOfDownloaded,".",programFileNameExtension,collapse = ".") 
  fileName<- list(
    new = programFileNameNew,
    old = programFileNameOld
  )
  return(fileName)
}

newNameCollect <- character()
oldNameCollect <- character()
for(i in 1:dim(dataSubmit)[1]){
  #i<-1
  submission_i<-dataSubmit[i,]
  
  fileName<-newNamefun(dataSubmit[i,]$答案檔,i,numberOfDownloaded)
  ###
  # file_download<-drive_download(as_id(dataSubmit[i,]$答案檔))
  # file.rename(fileName$old,fileName$new)
  # file.copy(fileName$new,paste0(params$ansDir))
  ###
  ##print(getwd())
  drive_download(as_id(dataSubmit[i,]$答案檔),
                path=paste0(params$ansDir,"/",fileName$new),
                 overwrite = T)
  # drive_download(as_id(dataSubmit[i,]$答案檔),
  #               path=
  #                 paste0(
  #                   getwd(),
  #                   str_replace(params$ansDir,".",""),
  #                   "/",
  #                   fileName$new
  #                   ))
  
  newNameCollect <- c(newNameCollect, fileName$new)
  oldNameCollect <- c(oldNameCollect, fileName$old)
}
# 確保.Rmd 而非 .rmd .rMd等
str_replace(newNameCollect,regex("Rmd", ignore_case = T),"Rmd")->newNameCollect
dataSubmit$新檔名 <- newNameCollect
dataSubmit$原始檔名 <- oldNameCollect
```

## 上傳到GS 

```{r 在原GS記錄已下載}
# 計算原dataSubmit0這次下載的位置
dataSubmit0 %>% transmute(id=paste0(mdy_hms(Timestamp),學號)) %>% .$id -> id

cellNumberNewDownload <- which(id %in% newDownloadid)


#更新下載記錄
dataSubmit0$downloaded[cellNumberNewDownload]<-1
gs_edit_cells(gsSubmit,ws="Form Responses 1",
              input=dataSubmit0$downloaded, col_names = FALSE,
              anchor="G2")

```

# 檔案mapping更新

```{r}
dataSubmit %>% select(Timestamp,姓名,學號,原始檔名,新檔名) ->
  dataUpload

# 記錄processedTime
dataUpload$downloadTime<-Sys.time()

gsFileMap<-gs_key(params$gsFileNameMapping)

if(params$hwcode %in% gs_ws_ls(gsFileMap)){
  currentFileMap <- gs_read(gsFileMap,ws=params$hwcode)
  numberOfOldDownload <- nrow(currentFileMap)
  anchor=paste0("A",numberOfOldDownload+2)
  gs_edit_cells(gsFileMap,ws=params$hwcode,
                input=dataUpload, col_names = FALSE,
                anchor=anchor)
  
} else {
  gs_ws_new(gsFileMap,ws_title=params$hwcode,
            input=dataUpload, col_names = TRUE,
            anchor="A1")  
}
```

