---
title: "Grading with flexible methods"
author: "林茂廷"
output: html_document
params:
  filepath: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/Midterm/ans/MIDTERM-410773096.RDA"
  stepYfuns: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/StepY_funs.Rda"
  ansFilePath: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/Midterm/ans/MIDTERM-ANS.RDA"
  assistDir: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/Midterm/ans/assist"
  dataFiles: ["CLASSSURVEY.CSV","HWGRADES.CSV","HWSUBMIT.CSV"]
  chunkSheetFile: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/Midterm/ans/INFO/CHUNKSHEET.RDA"
  gsURL: "https://docs.google.com/spreadsheets/d/16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA/edit#gid=1536232356"
  wsName: "MIDTERM"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = params$baseDir)
```


```{r}
library(tools)
library(purrr)
library(stringr)
library(dplyr)
library(knitr)
library(googlesheets)
library(readr)
load(params$stepYfuns)
```


## Step 1: 批改Rda

```{r}
gradeRDA(params$filepath,params$ansFilePath)-> results
```

## Step 2: 計算成績

```{r}
results %>% 
  select(contains("ans")) %>%
  {rowSums(.,na.rm=T)}*5.5 -> results$成績
```

## Step 3: 更新線上成績
```{r}
#gs_auth()
gs_key("16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA") -> gsKey
gsKey %>% gs_read(ws="Midterm") -> dataSubmit

workingPath<-dirname(params$filepath)
results$新檔名 <- paste0(params$wsName,"_",nrow(dataSubmit)+1,".RMD") 

results$新檔名 %>%
  {file.path(workingPath,"AFTER_GRADING",.)} %>%
file.copy(file.path(workingPath,paste0(results$原始檔案,".RMD")),.)
```
# 檔名以排名變更
```{r}
dataSubmit2 %>% 
  filter(!is.na(成績)) -> dataSubmit3
dataSubmit3 %>%  
{.$listOfRMDs} -> filesToCopy
# copy to NewNamePath
file.path(workingPath,"AFTER_GRADING") -> NewNamePath
NewNamePath %T>%
  {if(!dir.exists(.)) dir.create(.)} %>%
  {file.copy(filesToCopy,to=.,overwrite = T)}

# Rename Files
oldNames<-file.path(NewNamePath,basename(dataSubmit3$listOfRMDs))
newNames<-file.path(NewNamePath,dataSubmit3$新檔名)
file.rename(oldNames,newNames)

dataSubmit %>%
  left_join(
    dataSubmit3 %>% 
      select(學號,新檔名),
    by="學號"
  ) -> dataSubmit4
```

```{r}
gs_key(params$gskey) -> gsPrivate
if(params$hwcode %in% gsPrivate$ws$ws_title){
  dataSubmit2 %>% gs_edit_cells(gsPrivate,ws=params$hwcode,
                            input=.,
                            anchor="A1")
} else {
  dataSubmit2 %>% gs_ws_new(gsPrivate,ws=params$hwcode,
                            input=.,
                            anchor="A1")
}

```

## 複製有問題RMD

```{r, eval=F}
# copy to NewNamePath
ProblemFilesToCopy <- dataSubmit2 %>% 
  filter(is.na(成績)) %>%
  {.$listOfRMDs}
file.path(workingPath,"ProblemRmds") -> NewNamePath
NewNamePath %T>%
  {if(!dir.exists(.)) dir.create(.)} %>%
  {file.copy(ProblemFilesToCopy,to=.,overwrite = T)}

```


## 準備公開成績資料
```{r 上傳GS, eval=F}
wsNameTemp <- paste0(params$hwcode,"-",Sys.Date())
gsPublic<-gs_key(params$gsPublicKey)
gsCorrected<-gs_key(params$gskey)

if(wsNameTemp %in% gs_ws_ls(gsCorrected)){
  gs_edit_cells(gsCorrected,ws=wsNameTemp,
                input=mergedResults, col_names = TRUE,
                anchor="A1")
  gs_edit_cells(gsPublic,ws=wsNameTemp,
                input=publicResults, col_names = TRUE,
                anchor="A1")  
} else {
  gs_ws_new(gsCorrected,ws=wsNameTemp,
            input=mergedResults, col_names = TRUE,
            anchor="A1")  
  gs_ws_new(gsPublic,ws=wsNameTemp,
              input=publicResults, col_names = TRUE,
              anchor="A1")

}

mergedResults %>% filter(上傳檔正常==FALSE) %>%
  {paste0(workingPath,"/",.$新檔名)} -> problemFiles
#file.remove(paste0(workingPath,"/problem"))
problemDir<-paste0(workingPath,"/problem")
file.copy(problemFiles,to=problemDir)
#file.remove(listOfRs)
```
