---
title: "處理問題期中試卷"
author: "林茂廷"
date: "11/19/2018"
output: html_document
params:
  workingPath: "/Midterm/ans/PROBLEMRMDS" 
  deadline: 2018-11-12
  hwcode: Midterm
  baseDir: "/Users/martin/Desktop/GitHub/course-107-1-programming-for-data-science/"
  gsFileNameMapping: "1J9A6We6cdDfOT-11gBgbHC9Qzqu0d457aquy5k1IOCc"
  gsClassInfo: "1E1P2na_-iRzczWxRVa09ldjE9NMidJOX0RGw9muhZfw"
  gsFileUpload: "1G8NjBYgWcQFVT8ms4c5HmWp19V_DvJ5u1rEKVNLRmZs"
  gsHWExams: "16XPjoHB_Pt7Vwby5QFwqFO2fW-rJahS4xyijiX2S8CA"
  markOffItems: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(googlesheets)
library(lubridate)
library(stringr)
library(readr)
library(stringr)
library(googledrive)
library(tools)
library(purrr)
library(rlang)
#gs_auth(new_user = TRUE)
load(file.path(params$baseDir,"StepY_funs.Rda"))
paste0(params$baseDir,params$workingPath) -> workingPath
```

```{r}
list.files(workingPath) %>% # 檔名全大寫
  {file.rename(
    paste0(workingPath,"/",.),
    to=paste0(workingPath,"/",toupper(.))
  )} 

listOfRMDs <- list_files_with_exts(workingPath,"RMD") 
# exclude ORIGIN
listOfRMDs %>%  str_detect("(-ORIGIN)") %>%
  {listOfRMDs[!(.)]} -> listOfRMDs
  
# choose corrected
#listOfRMDs <- listOfRMDs %>% str_subset("(-C\\.RMD)")

```

```{r}
#file.remove(listOfRs)
listOfRs <- file.path(
  workingPath,
  {basename(listOfRMDs) %>%
      str_replace("(RMD)","R")}
)

#purrr::map(1:length(listOfRMDs),knitr::purl) -> purlInfo

for(i in seq_along(listOfRMDs)){
 knitr::purl(listOfRMDs[i],output=listOfRs[i]) 
}


dataSubmitToProcess <- data.frame(
  listOfRMDs=listOfRMDs,
  canProduceR=T,
  shortNames=(listOfRMDs %>% basename %>%
                str_replace("\\.(RMD)",""))
)
```


```{r}
## markoff Data lines
#studentRs<-listOfRs
#listOfRsNoAns<-listOfRs
load(paste0(dirname(workingPath),"/CHUNKSHEET.RDA"))->chunkSheetFile
load(file.path(dirname(workingPath),"MIDTERM-ANS.RDA"))->ansRdaFile

markOff(listOfRs,params,chunkSheetFile)
```

## 執行學生R

```{r}
### 原始有問題的改成-origin保留
list_files_with_exts(workingPath,"RMD") -> allRmds
allRmds %>%  str_subset("(-C\\.RMD)") -> cList
allRmds %>% setdiff(cList) -> noncList
file.rename(noncList, str_replace(noncList,"(\\.RMD)","-ORIGIN.RMD"))
file.rename(cList,str_replace(cList,"(-C)",""))

listOfcRs <- list_files_with_exts(workingPath,"R") 
listOfcRs %>% str_replace("(-C)","")-> listOfRs
file.rename(listOfcRs,listOfRs)
listOfRs %>% chunkExtraction() -> chunkSheetNew
catchListFun(listOfRs,chunkSheetNew,workingPath,dataEnv=dataEnv)
```

